<RBoxWidget>:
    BoxLayout:
        spacing: 10
        orientation: 'vertical'
        Label:
            text: '[color=ff3333]WELCOME[/color] by [b]Loitd[/b]'
            markup: True
        Button:
            text: 'Press me'
            on_press: app.on_press_button()

<GUI0302>:
    GridLayout:
        id: container
        cols: 2
        RBoxWidget:
        RBoxWidget:
        RBoxWidget:
        RBoxWidget: